name: s3-deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: sed api endpoint
        run: |
          sed -e 's@ENDPOINT HERE@${{ secrets.AWS_API_ENDPOINT }}@g' js/main.js > js/main.js

      - name: deploy
        run: |
          aws s3 sync . ${{ secrets.AWS_S3_BUCKET_NAME }} --delete --exclude "README.md" --exclude ".git/*" --exclude ".github/*"
